### ISSUE TITLE
Syntax error on startup of Jupyterhub service

### ISSUE THREAD

**Issue by mikecroucher** [mikecroucher/jupyterhub_on_azure#15]
On trying to run this today, I recieved the error detailed at https://github.com/jupyterhub/jupyterhub/issues/2332

**Comment by mikecroucher** [comment]
My version is 

```
npm version

{ npm: '3.5.2',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '55.1',
  modules: '46',
  node: '4.2.6',
  openssl: '1.0.2g',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
```

**Comment by mikecroucher** [comment]
The script installs npm as follows

```
sudo apt-get -y install npm
```

This worked until recently.

**Comment by mikecroucher** [comment]
```
npm -version

3.5.2

node -v

v4.2.6
```

**Comment by mikecroucher** [comment]
I tried a bunch of node and npm upgrade commands on the failed instance. Not sure which one did the job because the version only seemed to change on reboot.  Not sure what's going on there but anyway....

I now have 

```
 node -v
v11.4.0

npm -version
6.5.0
```

and the result of 
```
/usr/local/bin/jupyterhub -f /etc/jupyterhub/jupyterhub_config.py --JupyterHub.spawner_class=sudospawner.SudoSpawner
```

is
```
15:32:56.100 [ConfigProxy] error: Uncaught Exception
15:32:56.101 [ConfigProxy] error: Uncaught Exception
[C 2018-12-11 15:33:06.966 JupyterHub app:1867] Failed to start proxy
```

**Comment by mikecroucher** [comment]
So now it fails after installation but works just fine after a reboot. Why!?!

**Comment by mikecroucher** [comment]
The jupyterhub launch command works when run as sudo but not as azureuser.

**Comment by mikecroucher** [comment]
Fixed with `sudo setcap 'cap_net_bind_service=+ep' `which node`
I had previously run this on `which nodejs` but this no longer seems to work.  Perhaps the update to node broke it

**Comment by davidedelvento** [comment]
Actually the problem does not seem to be the version of npm. See my comment at https://github.com/jupyterhub/jupyterhub/issues/2332#issuecomment-448772651 for details.
