### ISSUE TITLE
Master directory for data / scripts etc

### ISSUE THREAD

**Issue by mikecroucher** [mikecroucher/jupyterhub_on_azure#2]
Make a master directory which is readable by all (to store larger datasets and copy over notebooks etc.)

**Comment by mikecroucher** [comment]
Easiest way would be to create a user account where all files are world-readable.

Alternatively, mount a bucket on the VM and use that. It would then persist across VM instances.

**Comment by cathrynbirch** [comment]
A user account where all files are world-readable would be fine. How are you expecting setting this up to work? Are you essentially the administrator, i.e. will you set up all the accounts with the correct permissions for me and the students?

**Comment by mikecroucher** [comment]
At the moment, I am setting up everything so that the server you eventually use will be automatically built from scratch following a single command.

Once we have a server we are happy with, I can be the administrator or you can. Whatever you prefer.
For the world-readable files, I'll get an account set up that you can write to it.
You should be as autonomous as you need to be.

I'd like to set up the data, and the student home directories so that they are independent of the server VM. That is, if we mess up the server we can just build a new one....attach it to the storage and carry on.

This will be easy for the data (I think...testing it now) but I'm not quite sure how to do it for the home directories yet.  Might not have this in place for the home directories by the time you start using it.

**Comment by cathrynbirch** [comment]
Ok, let us know when we can access the new version of the server. Both Beth and I tried today but wouldn't load. Presumably you're working on it.

btw I have just had the student numbers through and we are looking at 20-25 students this year (uncertainty as MRes students haven't picked their modules yet).

**Comment by mikecroucher** [comment]
As discussed, we have a 10Gb drive mounted as /datadrive that will persist across iterations of this server.
