### ISSUE TITLE
Are user accounts/master copies backed up?

### ISSUE THREAD

**Issue by mikecroucher** [mikecroucher/jupyterhub_on_azure#4]
This was a question from an academic who wants to use it. 

Question is, what should we do here?  So many potntial solutions!

**Comment by cathrynbirch** [comment]
The students will be doing assessed coursework in Python notebooks, so some kind of backup is essential I think. The ideal situation for me would be to have a similar system to how the research disks are backed up in SEE (I think this is a a set of incremental backups stored going back a month, week and day? - you probably know better than me Mike). The volume of data needed for undergraduate teaching isn't huge but might this get unworkable in the future?

**Comment by mikecroucher** [comment]
Going to use rsnapshot for this and a separate backup disk mounted as /backup

**Comment by mikecroucher** [comment]
This has been configured. Testing on a VM now

**Comment by mikecroucher** [comment]
Works fine.
